In [11]:
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm 

In [8]:
events = list()
machines = list()
with open('../data/hdfs_test_normal') as infile:
    lines = infile.readlines()
    line0 = lines[0]
    print(line0.split())
    for event in map(int,line0.split()):
        events.append(event)


['5', '5', '5', '22', '11', '9', '11', '9', '11', '9', '26', '26', '26', '23', '23', '23', '21', '21', '21']


In [28]:
n_events=np.array(events)
n_events


array([ 5,  5,  5, 22, 11,  9, 11,  9, 11,  9, 26, 26, 26, 23, 23, 23, 21,
       21, 21])

In [30]:
machine_context = np.full(
    (n_events.shape[0],10),
    0,
    dtype =int,
    )

In [32]:
diff = n_events[1:]-n_events[:-1]

In [37]:
timeout_mask = diff >=0

In [38]:
timeout_mask

array([ True,  True,  True, False, False,  True, False,  True, False,
        True,  True,  True, False,  True,  True, False,  True,  True])

In [53]:
myarr=np.arange(10)
machine_context = np.full(
    (myarr.shape[0],10),
    -1,
    dtype =int,
    )

In [54]:
machine_context

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [55]:
myarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
machine_context[1:,9]=myarr[:-1]

In [57]:
machine_context

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  3],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  4],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  5],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  6],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  7],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  8]])

In [58]:
machine_context[2:,8]=myarr[:-2]

In [59]:
machine_context

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1,  0,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1,  1,  2],
       [-1, -1, -1, -1, -1, -1, -1, -1,  2,  3],
       [-1, -1, -1, -1, -1, -1, -1, -1,  3,  4],
       [-1, -1, -1, -1, -1, -1, -1, -1,  4,  5],
       [-1, -1, -1, -1, -1, -1, -1, -1,  5,  6],
       [-1, -1, -1, -1, -1, -1, -1, -1,  6,  7],
       [-1, -1, -1, -1, -1, -1, -1, -1,  7,  8]])

In [61]:
machine_context[3:,7]=myarr[:-3]

In [62]:
machine_context

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1,  0,  1],
       [-1, -1, -1, -1, -1, -1, -1,  0,  1,  2],
       [-1, -1, -1, -1, -1, -1, -1,  1,  2,  3],
       [-1, -1, -1, -1, -1, -1, -1,  2,  3,  4],
       [-1, -1, -1, -1, -1, -1, -1,  3,  4,  5],
       [-1, -1, -1, -1, -1, -1, -1,  4,  5,  6],
       [-1, -1, -1, -1, -1, -1, -1,  5,  6,  7],
       [-1, -1, -1, -1, -1, -1, -1,  6,  7,  8]])

In [39]:
machine_context[1:,9]=np.where(timeout_mask,-1,n_events[:-1])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
myList = ['a','b','c','d']
mapping = {i: event for i, event in enumerate(myList)}

In [17]:
df = pd.DataFrame({'Animal':['Falcon','Falcon','Parrot','Parrot'],'Max Speed':[380,370,24,26]})
df

Animal  Max Speed
0  Falcon        380
1  Falcon        370
2  Parrot         24
3  Parrot         26

In [22]:
a= tqdm(df.groupby('Animal'))


  0%|          | 0/2 [00:00<?, ?it/s]